### PR TITLE
android build

### PR DESCRIPTION
**Pull request by abe-winter**
## What changed
- makefile
- bump rdk to 0.20.0
- download droid aar file and unpack onnx .so
- `-test-import` flag for DLL testing
## Notes
ndk paths in makefile will be slightly different on mac

### CODE REVIEW

**Review by bhaney — APPROVED** [review]
Oh wow! Was it really this simple? I'm hopeful

**Comment by abe-winter** [comment]
actually don't merge it yet, this was before you explained `.so` files

**Review by bhaney — APPROVED** [review]
Cool! Its awesome you were able to find the runtime so quickly!

**Comment by abe-winter** [comment]
solid framework, they made it surprisingly easy

**Pull request merged**
